# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'MovieTexture' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods

pod 'Moya/RxSwift'
pod 'Moya'
pod 'RxSwift'
pod 'RealmSwift'
pod 'PromiseKit'
pod 'Texture'

end


